### ISSUE TITLE
unable to open the .txt file with QTodoTxt if the location is changed

### ISSUE THREAD

**Issue by razvanenescu** [mNantern/QTodoTxt#109]
To replicate - open the application and insert a task; save to a file location.

Move the file location; open the application and use File->Open - QTodoTxt will not be able to see the txt file neither by using the "Text Files" filter or the "All files" filter.

I am using Linux Mint 17 (Ubuntu 14.04) and I installed the application using the ".deb" package you provided.

If I use the system filemanager I can see the txt file and I can open it with a text editor.

Thanks for fixing this!

**Comment by funkyfuture** [comment]
closing due to non-feedback.
