### ISSUE TITLE
Proposal : remove the "auto-save" option

### ISSUE THREAD

**Issue by mNantern** [mNantern/QTodoTxt#121]
At first "auto-save" was an option because it wasn't enough tested but now after 3 versions (at least) with it, it seems to work well.

I want to remove the option in File > Preferences and leave it activated by default.

What do you think ?

**Comment by benjabean1** [comment]
I vote no.
IMO, giving the users choice is always the best option. Some users may not want auto save.

**Comment by mNantern** [comment]
Not sure about that, I don't like when a tool has too much options. And if nobody is using it...

**Comment by funkyfuture** [comment]
there may be two approaches on that conflict of interests:
- toggle between few 'standard' options with good defaults and 'extended' options
- configure the availability of options (in a config-file and/or via checkboxes)

**Comment by cjrobe** [comment]
Another vote for extended options. Adding an option to enable extended options would only take one menu place, but could hide any number of extended options.

**Comment by andcoz** [comment]
At least one user does not want the "auto-save": I. 
Please, keep it optional.

**Comment by mNantern** [comment]
OK si we leave it like that !

Thanks for your comment
