### ISSUE TITLE
[feature] manage recurring tasks

### ISSUE THREAD

**Issue by aurisnoctis** [mNantern/QTodoTxt#127]
I think it is a nice idea to integrate recurring tasks as in Simpletask for Android (https://github.com/mpcjanssen/simpletask-android/blob/master/src/main/assets/index.md):

> * Recurrence with rec:[0-9]+[dwmy] as described here but with a twist.
 * By default Simpletask will use the dates in that task to create the recurring task not the date of completion as described in the link. This behaviour can be configured from the settings.
 * The format is described by a regular expression, so in words the syntax is rec: followed by 1 or more numbers (the +) followed by one of day, week, month or year. For example `rec:12d` sets up a 12 day recurring task.

One more issue that popped up with this nice feature was that once the task is completed, the new task could either be scheduled for the original date + recurrence time OR for the day of completion + recurrence time. In Simpletask, this is a part of the preferences. To keep it simple, I would say that recurrence with respect to the original date is more common, as regular chores usually appear once per week, per month, ... and don't usually shift in time.

**Comment by mimmori** [comment]
Nice feature! +1

**Comment by funkyfuture** [comment]
there's [another approach](https://github.com/ginatrapani/todo.txt-cli/wiki/Todo.sh-Add-on-Directory#recur-intelligently-add-recurring-tasks) to this in the list of add-ons for the 'original' `todo.txt`. for long-term compatibility i'd stick to this.

i don't like the idea to configure the behaviour as Simpletask does. but in opposite to the add-on linked above, it's nice to have the recurrence-definition within the task itself.

**Comment by funkyfuture** [comment]
oh, and please look at existing issues before opening a new one: #86 

so, there are three more or less different designs proposed/known for this feature.

**Comment by aurisnoctis** [comment]
Hi @funkyfuture ,

yes, I agree with both: I had seen the add-ons page for todo.txt-cli and recurring tasks, and think it's a good idea not to fork off too much, but also not liking the extra file too much ...

After all, these are "just" add-ons for todo.txt-cli, and not maintained within the todo.txt-cli repository itself as official syntax, so if anyone adapted the `rec:[0-9]+[dwmy]` method as add-on for todo.txt-cli, it would have the same justification as the current add-ons now.

Re `please look at existing issues`, I did, and nothing came up in the search (except my own entry) - see attached images.

![screen1](https://cloud.githubusercontent.com/assets/8195964/6022676/dfb77520-abbe-11e4-862e-69cc0a2941fc.png)
![screen2](https://cloud.githubusercontent.com/assets/8195964/6022679/e5709cb2-abbe-11e4-91ea-513ca01df88b.png)

**Comment by aurisnoctis** [comment]
I will close this issue now, since #86 by @mimmori is exactly the same idea, with exactly the same wish for implementation as `rec:[0-9]+[dwmy]`.

Sorry again for duplicating! (I'd be grateful for someone told me why my search for 'recur' didn't bring up anything.)
