### ISSUE TITLE
Two feature requests to do with due dates

### ISSUE THREAD

**Issue by cjrobe** [mNantern/QTodoTxt#131]
Right now due dates take the backburner - they're highlighted but they don't get sorted above tasks with no due dates and there's no way to view tasks that are due soon. I have two to improve the usage of due dates. 

1. Due dates are sorted within a priority.
eg1. So something due tomorrow with a priority B would be at the top of all the B priority tasks.
eg2. If there is no priority listed but a due date is given, it goes at the top of the no priority tasks.

2. Add a due date filter. Due dates take priority over priority, The tasks due first or past due would show up high on the list.
eg1. "Due in the week" shows only tasks that are due within the next week (and in the past). Add multiple date selections ("Due within the next day", "Due in the next month" etc).

**Comment by funkyfuture** [comment]
the first point is on my todo for the rework of the `Task`-class.

**Comment by funkyfuture** [comment]
filters for due-dates re implemented by @jo-tud.

so, both is on its way. be patient or hack!
