### ISSUE TITLE
upgrade from 1.3 to 1.4 on windows doesn't work properly

### ISSUE THREAD

**Issue by sander76** [mNantern/QTodoTxt#132]
overwriting my old installation with the 1.4 didn't work. Starting the application resulted in a crash without any message or something.
I renamed the .qtodotxt.cfg to .bak and all worked fine !

**Comment by mimmori** [comment]
already discussed!

**Comment by sander76** [comment]
Okay. Did an issue search. Apparently not good enough.... Thanks.

**Comment by mimmori** [comment]
you can find it in the closed issue list [V1.4 Not run #102].

Ciao!
