### ISSUE TITLE
How to start to contribute the project

### ISSUE THREAD

**Issue by mimmori** [mNantern/QTodoTxt#133]
Hi , I am writing to ask some details for starting contributing this project.

I am new to python world but I already program in other language ( C / C ++  using VCL and MFC for graphics). I have Studied python language but I am a bit confused about the gui development. I have seen that QTodoTxt use PySide framework so I decided to start here.

- Do you have some general tips or advice to give me?
- Does QTodoTxt graphics was written by scratch or using some RAD or GUI Builder?
- Do you have some advise for good guide?

Thanks in advance.
Domenico

**Comment by mNantern** [comment]
For the GUI I do everything by hand with the PySide doc (and a lot of googling !)

I think that the best way to learn python is by practicing it. Take a task and try to solve it, if it's difficult ask for help.
If you want a good book to learn Python I like http://learnpythonthehardway.org/book/

You can use the Google Groups for QTodoTxt to ask that kind of question: https://groups.google.com/forum/#!forum/qtodotxt

Hope it helps !

**Comment by funkyfuture** [comment]
i can recommend these books as a good read and reference:
- Dusty Philip's [Python 3 -OOP](https://www.packtpub.com/application-development/python-3-object-oriented-programming)
- Doug Hellman's [The Python Stamdard Library by Example](http://doughellmann.com/pages/python-standard-library-by-example.html) (though, quiet outdated)
- Mark Lutz' [Python Pocket Reference](http://shop.oreilly.com/product/0636920028338.do)
- and of course the docs and wiki at http://python.org

luckily there's no lack of online resources. and a great community.

----

as you seem to be interested in GUI-hacking, you may have a look on my rewrite of the Task-library which eventually fails when it comes to rendering (tests are passing and the task-file is written correctly):

- #94 
- https://github.com/funkyfuture/QTodoTxt/tree/lib-task

atm i can't find any elaborations where i describe the problem, but it's around the debug-loggings in [tasks_list_view.py](https://github.com/funkyfuture/QTodoTxt/blob/master/qtodotxt/ui/views/tasks_list_view.py) where i lose track.
