### ISSUE TITLE
TestAutoCompleteLineEdit fails 

### ISSUE THREAD

**Issue by funkyfuture** [mNantern/QTodoTxt#135]
```
self = <test_autocomplete_lineedit.TestAutoCompleteLineEdit testMethod=test_check_ctor>

    def test_check_ctor(self):
>       self.assertEqual(AutoCompleteEdit(['one', 'two'])._separator, ' ')
E       TypeError: __init__() missing 1 required positional argument: 'autocomplete_pairs'

QTodoTxt/qtodotxt/test/ui/test_autocomplete_lineedit.py:13: TypeError
```

obviously the call of `AutoCompleteEdit.__init__` is using a wrong signature. @jo-tud, what would the argument `model` expect to get passed?

**Comment by jo-tud** [comment]
model expects a list of strings such as
values = ['(A)', '(B)', '(C)', '@home', '@call', '@work', '+qtodotxt', '+sqlvisualizer']
the list contains known strings that will be suggested. Autocomplete pairs, on the other hand, is a dictionary containing "commands" that will be replaced. e.g. *due:Febuary* will be replaced by *due:2016-02-28*.

**Comment by funkyfuture** [comment]
thanks for the explanation, can you make a patch that includes that as inline-documentation in the code?

i'm currently on the  road and can't look into the code. but what would be the correct testcase?

**Comment by funkyfuture** [comment]
now i'm really confused. anyway.

up there i'm quoting the output that refers to a `test_autocomplete_lineedit.py` with a unittest. however this file doesn't exist. i don't have any clue where that came from.

however please don't use doctest, but unittest, which is in the long term much better to maintain.

**Comment by funkyfuture** [comment]
the file was in another branch when i looked for it…

here's how i translated it:
```
from PySide import QtGui
from qtodotxt.ui.controls.autocomplete_lineedit import AutoCompleteEdit
import unittest


class TestAutoCompleteLineEdit(unittest.TestCase):
    def setUp(self):
        self.app = QtGui.QApplication.instance()
        if not self.app:
            self.app = QtGui.QApplication([])

    def test_check_ctor(self):
        self.assertEqual(AutoCompleteEdit(['one', 'two'], {'foo':'bar','kung':'fu'})._seperator, ' ')
```

please reopen this issue if there's space for improvement.
