### ISSUE TITLE
Documentation outside project

### ISSUE THREAD

**Issue by SimonChristopherCropper** [mNantern/QTodoTxt#141]
GitHub is a good system but unfortunately their repository wikis are outside the project so can not be managed in the same way as the code base.

Might I suggest you create a subdirectory called 'documentation' in the main repository and save the wiki's markdown files in there. That way people offering pull requests can update the documentation to reflect the new functionality.

For example, I have updated your code base to include the ability to reference local resources and open the email client from within QTodoTxt using xdg-open hyperlink protocols. Unfortunately the documentation is stored in the wiki which can't be updated until you accept my pull request. If I forget or you don;'t do it as a matter of course that information will not be included in the documentation. If the markdown files are in a separate directory then this problem is avoided. Apart from updating the code I can also update the user documentation as well and you can review this when the pull request is processed.

Only an idea :)

**Comment by mNantern** [comment]
Actually you can download the wiki as a git repository: https://help.github.com/articles/adding-and-editing-wiki-pages-locally/

But I don't know if you can submit a PR on wiki page ?

**Comment by SimonChristopherCropper** [comment]
Personally I don't think having two repositories is the way to go. I think having a subdirectory called "documentation" under the project that includes your markdown files would be the best option. Then contributors can update just like the codebase.

You could then change your wiki to point to these files as discussed here http://stackoverflow.com/questions/6474045/linking-to-other-wiki-pages-on-github

**Comment by kmicc** [comment]
Do you have a working example of your suggestion? I tried to implement it. Inserting the wiki pages into the repository with the source code went well. But I didn't find a way to redirect from the github wiki page to that inserted files. The best thing I could get was a link like this one: [Go to the wiki page](https://github.com/kmicc/QTodoTxt/blob/wiki/Home.md). That's rather ugly, and if you want to edit the wiki pages, the markdown edit buttons are also missing. Thats not nice, despite the advantages you list above.

What might work: Edit the wiki in your cloned repository and let the repository owner manually merge the changes in your wiki to the official wiki. I'm pretty sure this will work, but it seems time consuming.

The third an maybe easiest solution: Save the changed wiki pages as a file and attach them to a comment in the pull request.

**Comment by SimonChristopherCropper** [comment]
Yeah, sorry I could not get it working cleanly either. In my fork I turned off the wiki and just store the markdown pages within the documentation folder.

Anyway this project seems to be dead. I have not seen any activity for months. There are multiple pull requests not been implemented and the travis build failed months ago due to a bad pull that has not been fixed.

I am only maintaining my forked version until I can rewrite something else. The lack of documentation in the code makes it very difficult to just pick this repo up and build on it further -- apart from little tweeks here and there.
