### ISSUE TITLE
Version number for QTodoTxt not being updated

### ISSUE THREAD

**Issue by SimonChristopherCropper** [mNantern/QTodoTxt#142]
I downloaded the repo binary file. The version was 1.4.0

As I wanted to update some code I forked the project. The program version was flagged as being the same as the binary I previously downloaded. When opening the program however it was clear that some important changes had occurred. For me the 'Due' category and 'Overdue, etc' subcategories jumped of the interface but I am sure that many other changes have occurred.

How are minor releases being tracked? Are they being tracked?

**Comment by mNantern** [comment]
They are not tracked, I change the version number just before releasing QTT.

So when you fork the HEAD of master you get the last version (1.4) + every commit since then.
