### ISSUE TITLE
Search filter not working with current Python / Pyside

### ISSUE THREAD

**Issue by dkaparis** [mNantern/QTodoTxt#154]
Under Arch Linux, the search filter stopped working after upgrade of Python from 3.4.3-3 to 3.5.0-2.
Typing in the bar doesn't filter anything and having entered text there actually freezes the currently displayed items when selecting different contexts/projects in the tree.

**Comment by funkyfuture** [comment]
which version of PySide are you using? 1.2.4 doesn't support Python 3.5 yet.

**Comment by dkaparis** [comment]
I'm using PySide 1.2.2 as that's what arch is carrying currently. I've flagged the packages in the arch community repository as out-of-date and will test again when they get updated.

I wasn't aware PySide was incompatible with Python 3.5 and couldn't find any definitive reference on that in docs. Can you point me to it?

**Comment by funkyfuture** [comment]
the installation with pip aborts with a message.

**Comment by martynjy** [comment]
Same here.  No search function on Arch with python 3.5.0-2 and python-pyside 1.2.4-1.

**Comment by dkaparis** [comment]
I've tested with the updated PySide 1.2.4 and the problem persists.
Regarding the possible incompatibility with Python 3.5, I've posted to the Arch forums, in search for a solution:
https://bbs.archlinux.org/viewtopic.php?pid=1578243#p1578243
I'll update here if any solution presents itself.

**Comment by dkaparis** [comment]
I have confirmed in my testing - with Python 3.4 and PySide 1.2.4, the search bar works properly (I used the python34 package from AUR, created a virtual environment with pyvenv-3.4 and manually installed PySide and ran qtodotxt from there).

This is a regression, however and if it is an issue with PySide, it should be reported upstream. 

@funkyfuture is there anything more I can do to help tracking down the issue on my end?

**Comment by martynjy** [comment]
Sorry to say but until the search function is fixed I will not be using this package!

**Comment by kmicc** [comment]
And what should we do here? Following this diskussion it seems for me up to now that this is a problem with external libraries, not with qtodotxt itself. Maybe you can use an older Python version (version 3.4 for example)?

**Comment by dkaparis** [comment]
It is not yet clear that this is the case.
The specific cause for the problem should be identified and if it is indeed a bug in an external library, reported upstream.
I have offered my help tracking down the issue, but currently don't have the time to spend doing it myself.
In the meantime, the only workaround for the current version would be to run it with Python 3.4.

**Comment by dkaparis** [comment]
Actually turned out it is not related to third party libraries.
On filter text field change, filters.py:351 calls `raise re.error` without arguments, which apparently fails under Python 3.5:

```
Traceback (most recent call last):
  File "[...]/QTodoTxt/bin/../qtodotxt/ui/controllers/main_controller.py", line 113, in _onFilterTextChanged
    tasks = todolib.filterTasks([SimpleTextFilter(text)], treeTasks)
  File "[...]/QTodoTxt/bin/../qtodotxt/lib/todolib.py", line 135, in filterTasks
    if filter.isMatch(task):
  File "[...]/QTodoTxt/bin/../qtodotxt/lib/filters.py", line 351, in isMatch
    raise re.error  # otherwise adding closing parenth avoids error here
TypeError: __init__() missing 1 required positional argument: 'msg'
```

The fix is to add an empty 'msg' argument to re.error creation; PR submitted.
On a more general note, I find this usage of exceptions to control normal logic flow of operation questionable.
