### ISSUE TITLE
Add new tree filter by due date

### ISSUE THREAD

**Issue by mNantern** [mNantern/QTodoTxt#21]
I used due date a lot (with "due:2013-10-01" for example) and it will be nice to have a new section on the left tree. Something like:

* Due
  * Today
  * Tomorrow
  * Later

**Comment by jo-tud** [comment]
+1. This would be really great!

**Comment by jo-tud** [comment]
I implemented this feature. There will be a pull request.

**Comment by mNantern** [comment]
Thanks a lot for the work ! I will look at it this week.
